version: '3'
services:
#  pig-mysql:
#    build:
#      context: ./db
#    environment:
#      MYSQL_ROOT_HOST: "%"
#      MYSQL_ROOT_PASSWORD: root
#    restart: always
#    container_name: pig-mysql
#    image: pig-mysql
#    ports:
#      - 3306:3306

#  pig-redis:
#    image: redis:7.0.0
#    ports:
#      - 6379:6379
#    restart: always
#    container_name: pig-redis

#  pig-register:
#    build:
#      context: ./pig-register
#    restart: always
#    ports:
#      - 8848:8848
#      - 9848:9848
#    container_name: pig-register
#    image: pig-register

  pig-gateway:
    build:
      context: ./pig-gateway
    restart: always
    container_name: pig-gateway
    image: pauly.fun:8009/pig-gateway
    network_mode: host
    extra_hosts:
      - "pig-redis:127.0.0.1"
      - "pig-register:127.0.0.1"
      - "pig-mysql:127.0.0.1"

  pig-auth:
    build:
      context: ./pig-auth
    restart: always
    container_name: pig-auth
    image: pauly.fun:8009/pig-auth
    network_mode: host
    extra_hosts:
      - "pig-redis:127.0.0.1"
      - "pig-register:127.0.0.1"
      - "pig-mysql:127.0.0.1"

  pig-upms:
    build:
      context: ./pig-upms/pig-upms-biz
    restart: always
    container_name: pig-upms
    image: pauly.fun:8009/pig-upms
    network_mode: host
    extra_hosts:
      - "pig-redis:127.0.0.1"
      - "pig-register:127.0.0.1"
      - "pig-mysql:127.0.0.1"
      - "pig-job:127.0.0.1"
      - "pig-seata:127.0.0.1"

  pig-monitor:
    build:
      context: ./pig-visual/pig-monitor
    restart: always
    container_name: pig-monitor
    image: pauly.fun:8009/pig-monitor
    network_mode: host
    extra_hosts:
      - "pig-redis:127.0.0.1"
      - "pig-register:127.0.0.1"
      - "pig-mysql:127.0.0.1"

  pig-codegen:
    build:
      context: ./pig-visual/pig-codegen
    restart: always
    container_name: pig-codegen
    image: pauly.fun:8009/pig-codegen
    network_mode: host
    extra_hosts:
      - "pig-redis:127.0.0.1"
      - "pig-register:127.0.0.1"
      - "pig-mysql:127.0.0.1"

#  pig-quartz:
#    build:
#      context: ./pig-visual/pig-quartz
#    restart: always
#    image: pig-quartz
#    container_name: pig-quartz
#    networks:
#      - spring_cloud_default
#
#networks:
#  spring_cloud_default:
#    name:  spring_cloud_default
#    driver: bridge
