server:
  port: 5002

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PWD}
      discovery:
#        ip: 10.0.0.2
        server-addr: ${NACOS_HOST:pig-register}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${NACOS_NAMESPACE}
  config:
    import:
      - nacos:application-@profiles.active@.yml
      - nacos:${spring.application.name}-@profiles.active@.yml
