name: 同步代码

on:
  push:
    branches: [ master,jdk17,jdk17-dev,dev ]
  pull_request:
    branches: [ master,jdk17,jdk17-dev,dev ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master #同步至 gitee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:pig-mesh/pig.git"
          destination-repo: "git@gitee.com:log4j/pig.git"
